name: Ruff Code Quality Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Ruff
      run: pip install ruff
      
    - name: Run Ruff check
      run: ruff check . --output-format=github
      
    - name: Run Ruff format check
      run: ruff format --check . --diff
      
    - name: Comment on PR (if applicable)
      if: failure() && github.event_name == 'pull_request'
      run: |
        echo "❌ Ruff kontrolü başarısız oldu!"
        echo "Lütfen kod kalitesi sorunlarını düzeltin."
